import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#272a32",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#363941",
        "surface-tint": "#4edea3",
        "on-background": "#e1e2ec",
        "surface-container": "#1d1f27",
        "surface-dim": "#10131a",
        "primary-container": "#10b981",
        "on-surface": "#e1e2ec",
        "on-primary-container": "#00422b",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#472a00",
        "background": "#10131a",
        "on-primary-fixed": "#002113",
        "surface": "#10131a",
        "error": "#ffb4ab",
        "surface-variant": "#32353d",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#32353d",
        "on-secondary": "#1000a9",
        "on-error": "#690005",
        "secondary-container": "#3131c0",
        "inverse-primary": "#006c49",
        "on-secondary-container": "#b0b2ff",
        "on-primary-fixed-variant": "#005236",
        "on-surface-variant": "#bbcabf",
        "tertiary-container": "#e29100",
        "tertiary-fixed": "#ffddb8",
        "primary": "#4edea3",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary": "#ffb95f",
        "secondary": "#c0c1ff",
        "on-tertiary-container": "#523200",
        "on-tertiary-fixed-variant": "#653e00",
        "outline": "#86948a",
        "outline-variant": "#3c4a42",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed-dim": "#4edea3",
        "surface-container-low": "#191b23",
        "inverse-on-surface": "#2d3038",
        "on-primary": "#003824",
        "primary-fixed": "#6ffbbe",
        "surface-container-lowest": "#0b0e15",
        "inverse-surface": "#e1e2ec",
        "on-secondary-fixed": "#07006c",
        "secondary-fixed": "#e1e0ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        margin: "1rem",
        "gutter-desktop": "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        gutter: "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "code-inline": ["Inter"],
        "headline-xl": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg": [
          "1.75rem",
          { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": [
          "1.125rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" },
        ],
        "label-md": [
          "0.875rem",
          { lineHeight: "1.25rem", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-xl-mobile": [
          "1.875rem",
          { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": [
          "0.8125rem",
          { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "400" },
        ],
        "headline-sm": [
          "1.25rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "1.5rem",
          { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "code-inline": [
          "0.8125rem",
          { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "500" },
        ],
        "headline-xl": [
          "2.5rem",
          { lineHeight: "3rem", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "body-md": [
          "0.9375rem",
          { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" },
        ],
        "label-sm": [
          "0.75rem",
          { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
